/*
 * generated by Xtext 2.22.0
 */
package de.tubs.skeditor.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ide.editor.syntaxcoloring.ISemanticHighlightingCalculator;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;

import de.tubs.skeditor.ide.SDLSemanticHighlighterCalculator;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SdlUiModule extends AbstractSdlUiModule {

	public SdlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator() {
		return SDLSemanticHighlighterCalculator.class;
	}
	
	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration() {
		return SDLHighlightingConfiguration.class;
	}
}
