/*
 * generated by Xtext 2.22.0
 */
package de.tubs.skeditor.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SdlUiModule extends AbstractSdlUiModule {

	public SdlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
