/*
 * generated by Xtext 2.22.0
 */
package de.tubs.skeditor.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.tubs.skeditor.SdlRuntimeModule;
import de.tubs.skeditor.SdlStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SdlIdeSetup extends SdlStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SdlRuntimeModule(), new SdlIdeModule()));
	}
	
}
