<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="SkillGraph" nsURI="www.thisisnotarealuri.de" nsPrefix="SkillGraph">
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abbreviation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="graph" lowerBound="1" eType="#//Graph"
        eOpposite="#//Graph/parameterList"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Graph">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" ordered="false"
        upperBound="-1" eType="#//Node" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootNode" lowerBound="1"
        eType="#//Node" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterList" upperBound="-1"
        eType="#//Parameter" containment="true" eOpposite="#//Parameter/graph"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" eType="#//Category"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="programPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="equations" upperBound="-1"
        eType="#//Equation" containment="true" eOpposite="#//Equation/node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childEdges" upperBound="-1"
        eType="#//Edge" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentNodes" unique="false"
        upperBound="-1" eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirements" upperBound="-1"
        eType="#//Requirement" containment="true" eOpposite="#//Requirement/node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Requirement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="term" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="a &lt; b &amp; b &lt; c"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" lowerBound="1" eType="#//Node"
        eOpposite="#//Node/requirements"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" unique="false"
        eType="#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Equation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" lowerBound="1" eType="#//Node"
        eOpposite="#//Node/equations"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="equation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Edge">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentNode" lowerBound="1"
        eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childNode" lowerBound="1"
        eType="#//Node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Category">
    <eLiterals name="main" literal="grey"/>
    <eLiterals name="observable_external_behavior" value="1" literal="yellow"/>
    <eLiterals name="perception" value="2" literal="green"/>
    <eLiterals name="planning" value="3" literal="lightblue"/>
    <eLiterals name="action" value="4" literal="orange"/>
    <eLiterals name="sensor" value="5" literal="blue"/>
    <eLiterals name="actuator" value="6" literal="red"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Type">
    <eLiterals name="Functional_Safety_Requirement" literal="FS"/>
    <eLiterals name="Technical_Safety_Requirement" value="1" literal="TS"/>
    <eLiterals name="Technical_Requirement" value="2" literal="T"/>
  </eClassifiers>
</ecore:EPackage>
