/*
 * generated by Xtext 2.22.0
 */
package de.tubs.skeditor;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SdlStandaloneSetup extends SdlStandaloneSetupGenerated {

	public static void doSetup() {
		new SdlStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
